Repository Polpetta/jkk, pull requests merged in 2020-01, with the labels that each got.

#9 WIP add dependency injection and mocks to tests
  build.gradle
  src/main/kotlin/it/polpetta/cli/Login.kt
  src/main/kotlin/it/polpetta/cli/Status.kt
  src/main/kotlin/it/polpetta/cli/Version.kt
  src/main/kotlin/it/polpetta/main.kt
  src/main/kotlin/it/polpetta/modules/JkkModule.kt
  src/main/kotlin/it/polpetta/utils/JenkinsSession.kt
  src/test/kotlin/it/polpetta/cli/VersionTest.kt
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: enhancement

#11 Change Jenkins client library
  .gitignore
  build.gradle
  src/main/kotlin/it/polpetta/api/jenkins/Api.kt
  src/main/kotlin/it/polpetta/api/jenkins/Build.kt
  src/main/kotlin/it/polpetta/api/jenkins/Job.kt
  src/main/kotlin/it/polpetta/api/jenkins/Version.kt
  src/main/kotlin/it/polpetta/api/jenkins/adapters/offbytwojenkins/Api.kt
  src/main/kotlin/it/polpetta/api/jenkins/adapters/offbytwojenkins/Build.kt
  src/main/kotlin/it/polpetta/api/jenkins/adapters/offbytwojenkins/Job.kt
  src/main/kotlin/it/polpetta/api/jenkins/adapters/offbytwojenkins/Version.kt
  src/main/kotlin/it/polpetta/cli/Login.kt
  src/main/kotlin/it/polpetta/cli/Status.kt
  src/main/kotlin/it/polpetta/cli/Version.kt
  src/main/kotlin/it/polpetta/utils/JenkinsSession.kt
  src/test/kotlin/it/polpetta/cli/VersionTest.kt
Labels: enhancement

#16 Add Docker image for CLI
  .dockerignore
  Dockerfile
Labels: enhancement

#22 Jar task to gradle and updated Dockerfile. This should fix #19
  Dockerfile
  build.gradle
Labels: automation, enhancement

#21 Some useful changes for packaging
  .travis.yml
  README.md
  pacur/PKGBUILD
Labels: automation, enhancement

#23 Enh/issue#10 - Implement better tests
  build.gradle
  src/main/kotlin/it/polpetta/cli/Login.kt
  src/main/kotlin/it/polpetta/files/FileButler.kt
  src/main/kotlin/it/polpetta/files/FileHandler.kt
  src/main/kotlin/it/polpetta/modules/JkkModule.kt
  src/main/kotlin/it/polpetta/utils/JenkinsSession.kt
  src/test/kotlin/it/polpetta/cli/LoginTest.kt
  src/test/kotlin/it/polpetta/cli/StatusTest.kt
  src/test/kotlin/it/polpetta/cli/VersionTest.kt
Labels: code, enhancement

#27 Fix #25 - Fat JAR task is now available for fat builds
  Dockerfile
  build.gradle
Labels: bug, enhancement
